language: python
python:
    - "3.5"
addons:
    apt:
        packages:
            - gcc-avr
            - avr-libc
            - doxygen
notifications:
    email: false

git:
  submodules: false

install:
    - pip install -r requirements.txt

script:
    tox
